### PR TITLE
Fixing dependency.

### PR DESCRIPTION
**Pull request by henvic**
concat-stream and try-thread-sleep are dependencies, not devDependencies. Or am I missing something?

### CODE REVIEW

**Comment by tomzx** [comment]
It is required @ 81ed72d97cd85982e167512420cd563f3e1b4500 in [spawn-sync.js] (https://github.com/ForbesLindesay/spawn-sync/blob/81ed72d97cd85982e167512420cd563f3e1b4500/lib/spawn-sync.js#L7).

**Comment by ForbesLindesay** [comment]
They should be installed by the `postinstall` script on platforms that don't natively support `cp.spawnSync`.  I take it that isn't working for you?

**Comment by tomzx** [comment]
@ForbesLindesay it does install correctly if I `npm install` in the spawn-sync folder, but it seems not to work when it is a dependency of another library/app.

**Comment by ForbesLindesay** [comment]
It should still work even in that situation

**Comment by tomzx** [comment]
Ignore my particular case. I had a *rogue* node in my path.

**Comment by henvic** [comment]
@tomzx, a rogue node in your path? Can you tell me more? I've used n to switch to 0.10.36 and I'm also having the same problem of spawn-sync not installing the needed dependencies.

@ForbesLindesay, okay. Now I understand how you do it. Pretty clever!

However, the current approach seems not to work when you're installing a global package. Can you please verify it?

Example:
This is related to https://github.com/node-gh/gh/issues/349.
If you install using `npm install -g https://github.com/node-gh/gh/tarball/2.0.x` it's not going to work.

But if you install locally, it does work.

Maybe it's installing on the wrong current working directory?

Also, what about if I intend to switch node versions to ones prior to 0.12? I'd have to reinstall my node packages. What if instead of avoiding to install the dependencies, just install it regardless if it's used or not (and just remove the postinstall script).

**Comment by tomzx** [comment]
@henvic, I had an old node executable in my path (thus rogue).

**Comment by henvic** [comment]
With the right executable does it just works? Interesting. Nor here.

**Comment by tomzx** [comment]
@henvic yes it works with the right executable.

**Comment by ForbesLindesay** [comment]
The problem is that while concat-stream is a cheap dependency to install, thread-sleep can potentially take a long time because it has to be compiled.  This is an especially big problem on things like raspberry pi's.  The other issue is that it emits angry error logs if it fails to build, and there's now way to tell people that those are for an optional dependency, so I'd rather that people on platforms that don't need it just don't get it.

**Comment by ForbesLindesay** [comment]
I've added concat-stream as an actual dependency, since it's not too much of a big deal to force people to download it (it's a tiny module that doesn't need compilation).  I've also made it so that if you run it without `try-thread-sleep` installed it will just log an angry warning and carry on working (although using all your CPU and hammering your hard drive).  Finally, I have fixed the postinstall.js script so it should now work even when spawn-sync gets installed globally.

**Comment by henvic** [comment]
Nice!

**Pull request closed without merging**
