### PR TITLE
Accept encoding options

### LINKED ISSUE #12: Strings, not buffer objects
the result object for the fallback method have Buffer objects on the `stdout` and `stderr` properties. 

iojs and 0.12 both return string values for them instead of buffer objects.

It would be good to fix this for a stardard utilization.

### PR DESCRIPTION
**Pull request by leobalter**
Closes #12

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
This is awesome.  Would you like to be added as a collaborator on this project, to help review and merge pull requests?

**Comment by leobalter** [comment]
Sure! Why not? o/

**Comment by ForbesLindesay** [comment]
Cool, you're added. Please follow these rules:

1. never commit directly to master unless you're only editing documentation, or you're in the process of cutting a new release.
2. never merge your own pull request unless it's had no comments from any collaborators for at least 24 hours.
3. If you cut a new release, make sure you follow [semver](http://semver.org/) when updating the version number.

If you let me know your npm username I'll add you as an owner so you can release new versions :)

**Comment by leobalter** [comment]
that's ok. My npm acc is the same as on github: @leobalter

**Comment by ForbesLindesay** [comment]
Thanks. I've added you as an owner :)

**Pull request merged**
